import { useMemo, useState } from "react";

type Mode = "day" | "week" | "month";
type AgendaPage = "home"|"notifications"|"agenda"|"lists"|"funnel"|"templates"|"reports"|"chips-users"|"settings";
type AgendaBootstrap = { profile?: { role?: string; full_name?: string } };
type Event = { id:string; client:string; company:string; bank:string; phone:string; start:string; end:string; type:string; status:string; chance:number; tone:string; online?:boolean };
const EVENTS: Event[] = [
  {id:"1",client:"Mariana Lopes",company:"Lopes & Lima",bank:"Santander",phone:"+55 11 98765-4321",start:"09:00",end:"09:45",type:"Reunião",status:"Confirmada",chance:82,tone:"green"},
  {id:"2",client:"Carlos Henrique",company:"CH Serviços",bank:"Bradesco",phone:"+55 11 91234-5678",start:"10:30",end:"11:15",type:"Reunião",status:"Agendada",chance:65,tone:"amber",online:true},
  {id:"3",client:"Juliana Costa",company:"Costa Comercial",bank:"Itaú",phone:"+55 47 99887-6655",start:"13:00",end:"13:30",type:"Follow-up",status:"Aguardando retorno",chance:48,tone:"teal"},
  {id:"4",client:"Renato Alves",company:"Alves Representações",bank:"Santander",phone:"+55 11 97654-3210",start:"14:30",end:"15:15",type:"Reunião",status:"Confirmada",chance:91,tone:"green",online:true},
  {id:"5",client:"Fernanda Lima",company:"Lima & Filhos",bank:"Bradesco",phone:"+55 11 94567-8901",start:"16:00",end:"16:30",type:"Follow-up",status:"Aguardando retorno",chance:32,tone:"red"},
  {id:"6",client:"Diego Albuquerque",company:"Albuquerque Ltda.",bank:"Santander",phone:"+55 11 99876-5432",start:"17:00",end:"17:45",type:"Contrato",status:"Agendada",chance:74,tone:"amber"},
];
const nav: Array<[AgendaPage,string,string,string]> = [["home","⌂","Início","Visão geral"],["notifications","♧","Notificações","Avisos da operação"],["agenda","▦","Agenda","Compromissos"],["lists","♙","Listas e Contatos","Leads e clientes"],["funnel","▽","Funis","Etapas e conversões"],["templates","▤","Modelos de Mensagens","Biblioteca"],["reports","▥","Relatórios","Desempenho"],["chips-users","▧","Chips e Usuários","Gestão"],["settings","⚙","Configurações","Preferências"]];

export default function AgendaOfficial({onNavigate, bootstrap, notify}:{onNavigate:(page:AgendaPage)=>void;bootstrap:AgendaBootstrap;notify:(text:string,tone?:"success"|"error")=>void}) {
  const [mode,setMode]=useState<Mode>("day"), [menu,setMenu]=useState(false), [filters,setFilters]=useState(false), [newEvent,setNewEvent]=useState(false), [selected,setSelected]=useState<Event|null>(null), [complete,setComplete]=useState<Event|null>(null);
  const [notes,setNotes]=useState(()=>localStorage.getItem("prospec-agenda-private-notes")||"");
  const [chance,setChance]=useState(70), [result,setResult]=useState("Cliente compareceu"), [next,setNext]=useState("");
  const top=useMemo(()=>[...EVENTS].sort((a,b)=>b.chance-a.chance).slice(0,5),[]);
  const days=["Seg 12/05","Ter 13/05","Qua 14/05","Qui 15/05","Sex 16/05","Sáb 17/05","Dom 18/05"];
  const month=Array.from({length:35},(_,i)=>i-2);
  const saveMeeting=()=>{notify("Reunião adicionada à Agenda, Timeline e Atendimento.");setNewEvent(false)};
  const finish=()=>{if(!next.trim()){notify("Informe os próximos passos.","error");return} notify(`Reunião concluída. Chance registrada em ${chance}% no histórico.`);setComplete(null);setNext("")};
  return <div className="agenda-shell">
    <aside className={`agenda-side ${menu?"open":""}`}><div className="agenda-brand"><i>✦</i><strong>PROSPEC <b>KR</b></strong><button onClick={()=>setMenu(false)}>×</button></div><nav>{nav.filter(([id])=>bootstrap.profile?.role==="admin"||id!=="chips-users").map(([id,icon,label,sub])=><button key={id} className={id==="agenda"?"active":""} onClick={()=>onNavigate(id)}><span>{icon}</span><b>{label}<small>{sub}</small></b></button>)}<button><span>?</span><b>Ajuda e Suporte<small>Central de ajuda</small></b></button></nav><div className="agenda-chip"><small>CHIP ATIVO</small><strong><i/> Chip 02</strong><span>+55 47 9 8405-980</span><button>⇄ Trocar chip</button></div></aside>
    {menu&&<button className="agenda-backdrop" onClick={()=>setMenu(false)}/>}<main className="agenda-main">
      <header className="agenda-top"><button className="agenda-menu" onClick={()=>setMenu(true)}>☰</button><div className="agenda-mobile-brand">PROSPEC <b>KR</b></div><label>⌕<input placeholder="Buscar contatos, empresas, tags..."/><kbd>Ctrl + K</kbd></label><span/><button>＋</button><button>♧<i>12</i></button><button>▣<i>3</i></button><button>▥</button><button>▦</button><button>⚙</button><div className="agenda-profile"><em>TK</em><b>{bootstrap.profile?.full_name||"Thainá Krause"}<small>{bootstrap.profile?.role==="admin"?"Administradora":"Advogado"}</small></b>⌄</div></header>
      <div className="agenda-body"><header className="agenda-heading"><div><h1>Agenda</h1><p>Gerencie suas reuniões, follow-ups e compromissos</p></div><button onClick={()=>setNewEvent(true)}>＋ Nova reunião</button></header>
        <section className="agenda-toolbar"><button>▦ Hoje</button><button>‹</button><button>›</button><strong>{mode==="month"?"Maio de 2025":mode==="week"?"12 a 18 de Maio de 2025":"15 de Maio de 2025"}</strong><div>{(["day","week","month"] as Mode[]).map(m=><button className={mode===m?"active":""} onClick={()=>setMode(m)} key={m}>{m==="day"?"Dia":m==="week"?"Semana":"Mês"}</button>)}</div><button onClick={()=>setFilters(true)}>☷ Filtros</button></section>
        <div className="agenda-content"><div className="agenda-central">
          {mode==="day"&&<DayView events={EVENTS} onOpen={setSelected}/>} {mode==="week"&&<WeekView events={EVENTS} days={days} onOpen={setSelected}/>} {mode==="month"&&<MonthView days={month}/>} {null}
        </div><Dashboard mode={mode} events={EVENTS} top={top} notes={notes} setNotes={setNotes} notify={notify}/></div>
      </div></main><MobileNav onNavigate={onNavigate}/><button className="agenda-fab" onClick={()=>setNewEvent(true)}>＋</button>
    {filters&&<Drawer close={()=>setFilters(false)}/>} {newEvent&&<MeetingForm close={()=>setNewEvent(false)} save={saveMeeting}/>} {selected&&<EventSheet event={selected} close={()=>setSelected(null)} complete={()=>{setChance(selected.chance);setComplete(selected);setSelected(null)}}/>} {complete&&<Complete event={complete} close={()=>setComplete(null)} chance={chance} setChance={setChance} result={result} setResult={setResult} next={next} setNext={setNext} save={finish}/>} {null}
  </div>
}

function DayView({events,onOpen}:{events:Event[];onOpen:(e:Event)=>void}){return <><section className="agenda-mobile-kpis">{[["Reuniões hoje","6","+20% vs ontem"],["Follow-ups hoje","4","+15% vs ontem"],["Novas indicações","1","+10% vs ontem"]].map(([a,b,c],i)=><article key={a} className={`k${i}`}><span>{a}</span><strong>{b}</strong><small>{c}</small></article>)}</section><section className="agenda-day"><header><h2>Agenda do dia</h2><button>Ver todas</button></header>{events.map(e=><article className={e.tone} key={e.id} onClick={()=>onOpen(e)}><time>{e.start}</time><em>{e.client.split(" ").map(x=>x[0]).slice(0,2).join("")}</em><div className="event-person"><strong>{e.client}</strong><small>{e.bank}</small><span>{e.type}</span>{e.online&&<span>Online</span>}</div><div className="event-contact">☎ {e.phone}<small>♜ {e.bank}</small></div><div className="event-date">▦ 15/05/2025<small>{e.start} – {e.end}</small></div><div className={`event-chance c${e.chance>=70?"good":e.chance>=50?"warn":"risk"}`}><small>Chance de fechamento</small><strong>{e.chance}%</strong><i><b style={{width:`${e.chance}%`}}/></i></div><button>Abrir</button><b className="event-more">⋮</b></article>)}</section><section className="agenda-follow"><header><h2>Follow-ups de hoje</h2><button>Ver todos</button></header><div>{events.slice(2,6).map(e=><article key={e.id}><em>{e.client[0]}</em><b>{e.client}<small>{e.bank}</small></b><time>{e.start}</time><span>{e.status}</span><button>☎</button></article>)}</div></section></>}
function WeekView({events,days,onOpen}:{events:Event[];days:string[];onOpen:(e:Event)=>void}){return <section className="agenda-week"><header><span/>{days.map(d=><b className={d.includes("15")?"today":""} key={d}>{d}</b>)}</header><div className="week-body"><aside>{Array.from({length:11},(_,i)=><span key={i}>{String(i+8).padStart(2,"0")}:00</span>)}</aside>{days.map((d,di)=><div key={d}>{events.filter((_,i)=>i%5===di%5).map((e,i)=><article className={e.tone} style={{top:40+i*130}} key={e.id} onClick={()=>onOpen(e)}><small>{e.start} – {e.end}</small><strong>{e.type} com {e.client}</strong><span>{e.bank}</span></article>)}</div>)}</div><footer>{days.map((d,i)=><span key={d}>{i===3?9:i===5?0:4+i%3} compromissos</span>)}</footer></section>}
function MonthView({days}:{days:number[]}){return <section className="agenda-month"><header>{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(x=><b key={x}>{x}</b>)}</header><div>{days.map((d,i)=><button className={`${d<1?"muted":""} ${d===15?"today":""}`} key={i}><strong>{d<1?d+30:d}</strong>{d>0&&i%3!==0&&<><span><i className="green"/>{i%6+1} eventos</span>{i%2===0&&<span><i className="amber"/>{i%3+1} follow-ups</span>}</>}</button>)}</div><footer><span><i className="green"/> Reuniões</span><span><i className="amber"/> Follow-ups</span><span><i className="orange"/> Outros compromissos</span></footer></section>}
function Dashboard({mode,events,top,notes,setNotes,notify}:{mode:Mode;events:Event[];top:Event[];notes:string;setNotes:(v:string)=>void;notify:(t:string)=>void}){return <aside className="agenda-dash"><section><header><h3>Resumo {mode==="day"?"do dia":mode==="week"?"da semana":"do mês"}</h3><button>Ver relatório</button></header><div className="agenda-summary">{[[mode==="month"?"76":"14","Reuniões","teal"],[mode==="month"?"43":"21","Follow-ups","green"],[mode==="month"?"28":"10","Agendamentos","amber"],[mode==="month"?"19":"6","Contratos fechados","red"]].map(([n,l,t])=><article className={t} key={l}><strong>{n}</strong><span>{l}</span><small>↑ 18% no período</small></article>)}</div></section><section className="agenda-next"><header><h3>Próximas reuniões</h3><button>Ver todas</button></header>{events.slice(0,3).map(e=><article key={e.id}><time>{e.start}</time><b>{e.client}<small>{e.bank}</small></b><em>{e.status}</em></article>)}</section><section className="agenda-top-opps"><header><h3>Top oportunidades</h3><button>Ver todas</button></header>{top.map((e,i)=><article key={e.id}><span>{i+1}</span><b>{e.client}<small>{e.bank}</small></b><i><em style={{width:`${e.chance}%`}}/></i><strong>{e.chance}%</strong></article>)}</section><section className="agenda-private"><header><h3>Notas pessoais</h3><button>＋ Nova nota</button></header><textarea value={notes} onChange={e=>setNotes(e.target.value)} onBlur={()=>{localStorage.setItem("prospec-agenda-private-notes",notes);notify("Anotação privada salva.")}} placeholder="Escreva suas anotações privadas aqui..."/><small>🔒 Somente você pode visualizar estas notas.</small></section></aside>}
function MobileNav({onNavigate}:{onNavigate:(p:AgendaPage)=>void}){return <nav className="agenda-mobile-nav"><button onClick={()=>onNavigate("home")}>⌂<small>Início</small></button><button onClick={()=>onNavigate("notifications")}>♧<small>Notificações</small></button><button className="active">▦<small>Agenda</small></button><button onClick={()=>onNavigate("lists")}>☷<small>Listas</small></button><button onClick={()=>onNavigate("reports")}>▥<small>Relatórios</small></button></nav>}
function Drawer({close}:{close:()=>void}){return <div className="agenda-overlay" onClick={close}><aside className="agenda-drawer" onClick={e=>e.stopPropagation()}><header><div><small>FILTROS DA AGENDA</small><h2>Refine os compromissos</h2></div><button onClick={close}>×</button></header>{["Responsável","Advogado","Tipo","Banco","Empresa","Lista","Status","Período","Google Meet","Formato","Chip"].map(x=><label key={x}>{x}<select><option>Todos</option></select></label>)}<footer><button>Limpar</button><button className="primary" onClick={close}>Aplicar filtros</button></footer></aside></div>}
function MeetingForm({close,save}:{close:()=>void;save:()=>void}){return <div className="agenda-overlay"><section className="agenda-form"><header><div><small>NOVO AGENDAMENTO</small><h2>Criar compromisso</h2></div><button onClick={close}>×</button></header><div>{["Título","Cliente","Empresa","Banco","Telefone","Responsável","Local"].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}<label>Tipo<select><option>Reunião</option><option>Follow-up</option><option>Ligação</option><option>Contrato</option><option>Prazo</option></select></label><label>Data<input type="date" defaultValue="2025-05-15"/></label><label>Hora inicial<input type="time" defaultValue="09:00"/></label><label>Hora final<input type="time" defaultValue="09:45"/></label><label>Prioridade<select><option>Normal</option><option>Alta</option><option>Urgente</option></select></label><label className="wide check"><input type="checkbox"/> Reunião online / Criar Google Meet</label><label className="wide">Observações compartilhadas<textarea/></label><label className="wide">Anexos<input type="file"/></label></div><footer><button onClick={close}>Cancelar</button><button className="primary" onClick={save}>Salvar agendamento</button></footer></section></div>}
function EventSheet({event,close,complete}:{event:Event;close:()=>void;complete:()=>void}){return <div className="agenda-overlay" onClick={close}><section className="agenda-sheet" onClick={e=>e.stopPropagation()}><header><div><small>FICHA DO AGENDAMENTO</small><h2>{event.type} com {event.client}</h2><em>{event.status}</em></div><button onClick={close}>×</button></header><div className="sheet-data">{[["Cliente",event.client],["Empresa",event.company],["Banco",event.bank],["Telefone / WhatsApp",event.phone],["Responsável","Matheus Moreira"],["Data e horário",`15/05/2025 · ${event.start}–${event.end}`],["Origem","Lista de Prospecção"],["Funil / Etapa","Atendimento · Reunião"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</div><div className="sheet-chance"><span>Chance de fechamento</span><strong>{event.chance}%</strong><input type="range" min="0" max="100" value={event.chance} readOnly/></div><div className="sheet-actions"><button>◉ Abrir WhatsApp</button><button>♙ Abrir CRM</button>{event.online&&<button className="meet">▣ Entrar na reunião</button>}<button className="primary" onClick={complete}>✓ Concluir reunião</button></div><section className="sheet-timeline"><h3>Timeline</h3><p><i/>Agendamento criado <small>Thainá · 15/05 às 08:32</small></p><p><i/>Chance alterada para {event.chance}% <small>Histórico preservado</small></p></section></section></div>}
function Complete({event,close,chance,setChance,result,setResult,next,setNext,save}:{event:Event;close:()=>void;chance:number;setChance:(n:number)=>void;result:string;setResult:(v:string)=>void;next:string;setNext:(v:string)=>void;save:()=>void}){return <div className="agenda-overlay"><section className="agenda-complete"><header><small>CONCLUSÃO OBRIGATÓRIA</small><h2>Como foi a reunião com {event.client}?</h2></header><label>Resultado<select value={result} onChange={e=>setResult(e.target.value)}>{["Cliente compareceu","Não compareceu","Reagendou","Sem interesse","Contrato enviado","Contrato fechado","Contrato perdido"].map(x=><option key={x}>{x}</option>)}</select></label><label>Chance de fechamento <strong>{chance}%</strong><input type="range" min="0" max="100" value={chance} onChange={e=>setChance(Number(e.target.value))}/><div>{[10,20,30,40,50,60,70,80,90,100].map(n=><button className={chance===n?"active":""} onClick={()=>setChance(n)} key={n}>{n}</button>)}</div></label><label>Próximos passos *<textarea value={next} onChange={e=>setNext(e.target.value)} placeholder="Informe obrigatoriamente os próximos passos"/></label><label>Selecionar advogado responsável<select><option>Matheus Moreira</option><option>Advogado disponível</option></select></label><label>Justificativa da alteração (opcional)<input placeholder="Ex.: cliente solicitou contrato"/></label><footer><button onClick={close}>Voltar</button><button className="primary" onClick={save}>Salvar conclusão</button></footer></section></div>}
