import { useCallback, useEffect, useMemo, useState } from "react";

/* eslint-disable @typescript-eslint/no-explicit-any */

type Row = Record<string, any>;
type Props = { bootstrap: Row; notify:(message:string,tone?:"success"|"error")=>void; apiAction:(action:string,payload?:Row)=>Promise<any> };
type Tab = "users"|"roles"|"chips";
const PAGE_PERMISSIONS:Array<[string,string]> = [["can_view_home","Início"],["can_view_agenda","Agenda"],["can_view_contacts","Listas e Contatos"],["can_view_recovery","Recuperação de Contatos"],["can_view_reports_overview","Relatórios (Visão Geral)"],["can_view_reports_my_performance","Relatórios (Meu Desempenho)"],["can_view_message_templates","Modelos de Mensagens"],["can_view_notifications","Notificações"],["can_manage_chips_users","Chips e Usuários"],["can_view_settings","Configurações"]];
const ACTION_PERMISSIONS:Array<[string,string]> = [["can_send","Enviar mensagens"],["can_manage_lists","Gerenciar listas"],["can_manage_contacts","Editar contatos"],["can_manage_recovery","Gerenciar recuperação"],["can_manage_templates","Gerenciar modelos"],["can_manage_reports","Exportar relatórios"],["can_manage_users","Gerenciar usuários"],["can_manage_chips","Gerenciar chips"]];
const statusLabel=(value:string)=>({active:"Ativo",pending:"Pendente",blocked:"Bloqueado",paused:"Pausado",restricted:"Restrito"}[value]||value||"—");
const initials=(name:string)=>String(name||"?").split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();
const healthTone=(score:number)=>score<=60?"healthy":score<=80?"attention":score<=95?"risk":"critical";

export default function ChipsUsersOfficial({bootstrap,notify,apiAction}:Props){
  const [tab,setTab]=useState<Tab>("users"); const [data,setData]=useState<Row>({profiles:[],invitations:[],permissions:{}}); const [chips,setChips]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [selectedUser,setSelectedUser]=useState<Row|null>(null); const [selectedChip,setSelectedChip]=useState<Row|null>(null); const [dialog,setDialog]=useState<"invite"|"chip"|"role"|null>(null); const [form,setForm]=useState<Row>({});
  const load=useCallback(async()=>{setLoading(true);try{const [u,c]=await Promise.all([apiAction("users"),apiAction("chips")]);setData(u||{profiles:[],invitations:[],permissions:{}});setChips(c||[]);setSelectedUser((old)=>old?(u?.profiles||[]).find((x:Row)=>x.id===old.id)||null:(u?.profiles||[])[0]||null);setSelectedChip((old)=>old?(c||[]).find((x:Row)=>x.id===old.id)||null:(c||[])[0]||null)}catch(e){notify(e instanceof Error?e.message:"Falha ao carregar.","error")}finally{setLoading(false)}},[apiAction,notify]);
  useEffect(()=>{load()},[load]);
  const profiles=useMemo(()=>[...(data.profiles||[]),...(data.invitations||[]).map((x:Row)=>({...x,status:"pending",invitation:true}))],[data]);
  const filteredUsers=profiles.filter((x:Row)=>`${x.full_name} ${x.email} ${x.job_title}`.toLowerCase().includes(query.toLowerCase()));
  const roles=useMemo(()=>{const map=new Map<string,Row>();profiles.forEach((u:Row)=>{const name=String(u.job_title||"Cargo não informado");const current=map.get(name)||{name,count:0,active:0};current.count++;if(u.status==="active")current.active++;map.set(name,current)});return [...map.values()].filter(x=>x.name!=="Cargo não informado")},[profiles]);
  const filteredChips=chips.filter(x=>`${x.name} ${x.number} ${x.operator}`.toLowerCase().includes(query.toLowerCase()));
  const permissions=selectedUser?{...(data.permissions?.[selectedUser.id]||{})}:{};
  const openInvite=()=>{setForm({role:"member",jobTitle:"",homePage:"inicio"});setDialog("invite")}; const openChip=(chip?:Row)=>{setForm(chip?{...chip,activatedAt:chip.activated_at,openingMethod:chip.opening_method||"app",appPackage:chip.app_package||""}:{status:"active",openingMethod:"app",health_score:0});setDialog("chip")};
  const saveDialog=async()=>{try{if(dialog==="invite")await apiAction("invite_user",{fullName:form.fullName,email:form.email,role:form.role,jobTitle:form.jobTitle,homePage:form.homePage});if(dialog==="chip")await apiAction("save_chip",form);if(dialog==="role"){if(!form.roleName?.trim())throw new Error("Informe o nome do cargo.");notify("Cargo pronto para ser atribuído aos usuários.")}setDialog(null);setForm({});await load();notify(dialog==="invite"?"Convite enviado por e-mail.":dialog==="chip"?"Chip salvo.":"Cargo criado.")}catch(e){notify(e instanceof Error?e.message:"Não foi possível salvar.","error")}};
  const saveUser=async()=>{if(!selectedUser||selectedUser.invitation)return;try{await apiAction("update_user",{userId:selectedUser.id,status:selectedUser.status||"active",role:selectedUser.role||"member",jobTitle:selectedUser.job_title||"",homePage:selectedUser.home_page||"inicio",permissions});notify("Usuário, cargo e permissões atualizados.");await load()}catch(e){notify(e instanceof Error?e.message:"Falha ao salvar.","error")}};
  const exportCurrent=()=>{const rows=tab==="chips"?filteredChips:tab==="roles"?roles:filteredUsers;const keys=[...new Set(rows.flatMap((r:Row)=>Object.keys(r).filter(k=>typeof r[k]!=="object")))];const csv=[keys.join(";"),...rows.map((r:Row)=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(";"))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=`prospec-${tab}.csv`;a.click();URL.revokeObjectURL(a.href)};
  const userCounts={total:profiles.length,active:profiles.filter((x:Row)=>x.status==="active").length,pending:profiles.filter((x:Row)=>x.status==="pending").length,blocked:profiles.filter((x:Row)=>x.status==="blocked").length};
  const chipCounts={total:chips.length,active:chips.filter(x=>x.status==="active").length,paused:chips.filter(x=>x.status==="paused").length,restricted:chips.filter(x=>x.status==="restricted").length,blocked:chips.filter(x=>x.status==="blocked").length};
  return <div className="cu-official" data-version="chips-usuarios-v3" data-session-role={bootstrap.profile?.role||"admin"}>
    <header className="cu-heading"><div><p className="eyebrow">GESTÃO ADMINISTRATIVA</p><h2>Chips e Usuários</h2><p>Gerencie usuários, cargos, permissões e acompanhe seus chips.</p></div><div><button className="secondary-button" onClick={exportCurrent}>⇩ Exportar lista</button><button className="primary-button" onClick={()=>tab==="users"?openInvite():tab==="roles"?(setForm({}),setDialog("role")):openChip()}>＋ {tab==="users"?"Convidar usuário":tab==="roles"?"Criar cargo":"Cadastrar chip"}</button></div></header>
    <nav className="cu-tabs">{[["users","Usuários"],["roles","Cargos"],["chips","Chips"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>{setTab(k as Tab);setQuery("")}}>{l}</button>)}</nav>
    <section className="cu-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ${tab==="users"?"usuário":tab==="roles"?"cargo":"chip"}...`}/></label><button onClick={load}>↻ Atualizar</button><span>Atualizado agora</span></section>
    {loading?<div className="cu-loading">Carregando dados reais…</div>:tab==="users"?<>
      <section className="cu-metrics">{[["Total de usuários",userCounts.total,"orange"],["Usuários ativos",userCounts.active,"green"],["Pendentes",userCounts.pending,"yellow"],["Bloqueados",userCounts.blocked,"red"]].map(([l,v,t])=><article className={String(t)} key={String(l)}><span>{l}</span><strong>{v}</strong><small>{userCounts.total?`${Math.round(Number(v)/userCounts.total*100)}% do total`:"Sem dados"}</small></article>)}</section>
      <div className="cu-split"><section className="cu-table-card"><div className="cu-table users"><b>Usuário</b><b>E-mail</b><b>Cargo</b><b>Status</b><b>Permissões</b>{filteredUsers.map((u:Row)=><button className={selectedUser?.id===u.id?"selected":""} key={u.id} onClick={()=>setSelectedUser(u)}><span className="cu-person"><i>{initials(u.full_name)}</i><span><strong>{u.full_name}</strong><small>{u.role==="admin"?"Administradora":"Usuário comum"}</small></span></span><span>{u.email||"—"}</span><span>{u.job_title||"Cargo não informado"}</span><span><em className={`pill ${u.status}`}>{u.invitation?"Convite pendente":statusLabel(u.status)}</em></span><span>{u.invitation?"Aguardando aceite":`${Object.values(data.permissions?.[u.id]||{}).filter(Boolean).length} permissões`}</span></button>)}</div>{!filteredUsers.length&&<div className="cu-empty">Nenhum usuário encontrado.</div>}</section>
      <aside className="cu-detail">{selectedUser?<><header><div className="cu-avatar">{initials(selectedUser.full_name)}</div><div><h3>{selectedUser.full_name}</h3><p>{selectedUser.email}</p></div></header>{selectedUser.invitation?<div className="cu-empty">O convite está pendente. As permissões poderão ser ajustadas após o aceite.</div>:<><div className="cu-fields"><label>Cargo<input value={selectedUser.job_title||""} onChange={e=>setSelectedUser({...selectedUser,job_title:e.target.value})}/></label><label>Página inicial<select value={selectedUser.home_page||"inicio"} onChange={e=>setSelectedUser({...selectedUser,home_page:e.target.value})}><option value="inicio">Início</option><option value="agenda">Agenda</option><option value="listas-contatos">Listas e Contatos</option><option value="relatorios">Relatórios</option></select></label><label>Status<select value={selectedUser.status||"active"} onChange={e=>setSelectedUser({...selectedUser,status:e.target.value})}><option value="active">Ativo</option><option value="pending">Pendente</option><option value="blocked">Bloqueado</option></select></label></div><h4>Permissões de páginas</h4>{PAGE_PERMISSIONS.map(([key,label])=><label className="cu-switch" key={key}><span>{label}</span><input type="checkbox" checked={permissions[key]===true} onChange={e=>setData((d:Row)=>({...d,permissions:{...d.permissions,[selectedUser.id]:{...permissions,[key]:e.target.checked}}}))}/><i/></label>)}<details><summary>Permissões de ações</summary>{ACTION_PERMISSIONS.map(([key,label])=><label className="cu-switch" key={key}><span>{label}</span><input type="checkbox" checked={permissions[key]===true} onChange={e=>setData((d:Row)=>({...d,permissions:{...d.permissions,[selectedUser.id]:{...permissions,[key]:e.target.checked}}}))}/><i/></label>)}</details><button className="primary-button full" onClick={saveUser}>Salvar usuário e permissões</button></>}</>:<div className="cu-empty">Selecione um usuário.</div>}</aside></div></>:
    tab==="roles"?<><section className="cu-metrics three">{[["Cargos cadastrados",roles.length,"orange"],["Usuários com cargo",profiles.filter((x:Row)=>x.job_title).length,"green"],["Sem cargo definido",profiles.filter((x:Row)=>!x.job_title).length,"yellow"]].map(([l,v,t])=><article className={String(t)} key={String(l)}><span>{l}</span><strong>{v}</strong><small>Atualização em tempo real</small></article>)}</section><section className="cu-role-grid">{roles.map((role:Row)=><article key={role.name}><div><span>◈</span><h3>{role.name}</h3></div><strong>{role.count}</strong><small>{role.active} ativos</small><button onClick={()=>{setTab("users");setQuery(role.name)}}>Ver usuários →</button></article>)}{!roles.length&&<div className="cu-empty">Nenhum cargo foi atribuído ainda.</div>}</section><section className="cu-note"><strong>Perfil, cargo e permissões são independentes.</strong><p>O nome digitado no campo Cargo substitui o rótulo funcional fixo nas áreas do sistema, enquanto o perfil administrativo e as permissões continuam controlando o acesso.</p></section></>:
    <><section className="cu-metrics five">{[["Total de chips",chipCounts.total,"orange"],["Ativos",chipCounts.active,"green"],["Pausados",chipCounts.paused,"yellow"],["Restritos",chipCounts.restricted,"rust"],["Bloqueados",chipCounts.blocked,"red"]].map(([l,v,t])=><article className={String(t)} key={String(l)}><span>{l}</span><strong>{v}</strong><small>{chipCounts.total?`${Math.round(Number(v)/chipCounts.total*100)}% do total`:"Sem dados"}</small></article>)}</section><div className="cu-split chips"><section className="cu-table-card"><div className="cu-table chips"><b>Chip</b><b>Número</b><b>Operadora</b><b>Status</b><b>Última atividade</b><b>Saúde</b>{filteredChips.map((chip:Row)=><button className={selectedChip?.id===chip.id?"selected":""} key={chip.id} onClick={()=>setSelectedChip(chip)}><span><strong>{chip.name}</strong><small>{chip.app_label||chip.opening_method||"Sessão não informada"}</small></span><span>+{chip.number}</span><span>{chip.operator||"—"}</span><span><em className={`pill ${chip.status}`}>{statusLabel(chip.status)}</em></span><span>{chip.last_activity_at?new Date(chip.last_activity_at).toLocaleString("pt-BR"):"—"}</span><span><em className={`health ${healthTone(Number(chip.health_score||0))}`}>{Number(chip.health_score||0)}</em></span></button>)}</div>{!filteredChips.length&&<div className="cu-empty">Nenhum chip encontrado.</div>}</section><aside className="cu-detail chip-detail">{selectedChip?<><header><div className={`sim-card ${healthTone(Number(selectedChip.health_score||0))}`}>▦</div><div><h3>{selectedChip.name}</h3><p>+{selectedChip.number} · {selectedChip.operator||"Operadora não informada"}</p></div><em className={`pill ${selectedChip.status}`}>{statusLabel(selectedChip.status)}</em></header><nav><button className="active">Resumo</button><button onClick={()=>notify("O histórico será exibido conforme os eventos forem registrados.")}>Histórico</button><button onClick={()=>notify("Saúde é uma estimativa interna baseada no histórico operacional.")}>Saúde</button></nav><section className="chip-summary"><article><span>Mensagens enviadas</span><strong>{selectedChip.messages_sent??"—"}</strong></article><article><span>Respostas</span><strong>{selectedChip.replies??"—"}</strong></article><article><span>Agendamentos</span><strong>{selectedChip.appointments??"—"}</strong></article><article><span>Reuniões</span><strong>{selectedChip.meetings??"—"}</strong></article></section><div className="health-panel"><span>Índice de saúde</span><strong>{Number(selectedChip.health_score||0)} / 100</strong><i><b style={{width:`${Math.min(100,Number(selectedChip.health_score||0))}%`}}/></i><small>Estimativa interna de risco; não prevê bloqueios com certeza.</small></div><button className="secondary-button full" onClick={()=>openChip(selectedChip)}>Editar chip</button></>:<div className="cu-empty">Selecione um chip.</div>}</aside></div></>}
    {dialog&&<div className="cu-modal-bg" onClick={()=>setDialog(null)}><section className="cu-modal" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">PROSPEC KR</p><h2>{dialog==="invite"?"Convidar usuário":dialog==="role"?"Criar cargo":"Cadastrar chip"}</h2></div><button onClick={()=>setDialog(null)}>×</button></header>{dialog==="invite"?<div className="cu-form"><label>Nome completo<input value={form.fullName||""} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>E-mail<input type="email" value={form.email||""} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Perfil<select value={form.role||"member"} onChange={e=>setForm({...form,role:e.target.value})}><option value="member">Usuário comum</option><option value="admin">Administrador</option></select></label><label>Cargo livre<input placeholder="Ex.: Advogado, SDR, Consultora" value={form.jobTitle||""} onChange={e=>setForm({...form,jobTitle:e.target.value})}/></label><p>O acesso será feito pelo link enviado ao e-mail, sem criação de senha.</p></div>:dialog==="role"?<div className="cu-form"><label>Nome do cargo<input autoFocus placeholder="Digite qualquer nome" value={form.roleName||""} onChange={e=>setForm({...form,roleName:e.target.value})}/></label><p>Depois de criado, use este nome no campo Cargo de qualquer usuário.</p></div>:<div className="cu-form"><label>Nome do chip<input value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Número com DDD<input value={form.number||""} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>Operadora<input value={form.operator||""} onChange={e=>setForm({...form,operator:e.target.value})}/></label><label>Status<select value={form.status||"active"} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Ativo</option><option value="paused">Pausado</option><option value="restricted">Restrito</option><option value="blocked">Bloqueado</option></select></label><label>Package do aplicativo<input placeholder="com.whatsapp" value={form.appPackage||""} onChange={e=>setForm({...form,appPackage:e.target.value})}/></label></div>}<footer><button className="secondary-button" onClick={()=>setDialog(null)}>Cancelar</button><button className="primary-button" onClick={saveDialog}>Salvar</button></footer></section></div>}
  </div>
}
